name: 'Terraform'

on:
  push:
    branches: ["main"]

jobs:
  terraform:
    name: 'Terraform'
    env:
      # AWS Secrets
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_DEVOPS_ACCESSS_AKEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_DEVOPS_SECRET_ACCESS_KEY}}

    runs-on: ubuntu-latest
    environment: production

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false

      # Initialize Terraform working directory
      - name: Terraform Init
        run: terraform init

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Generate Terraform plan
      - name: Terraform Plan
        run: terraform plan -no-color -input=false

      # Apply Terraform changes
      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color -input=
       # Destroy Terraform changes
      - name: Terraform Destroy
        run: terraform destroy